; Single 10mm extrusion line test
; generated by prusaslicer 2.7.0 on 2024-01-15 at 12:00:00 UTC
; perimeter_extrusion_width = 0.42
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; layer 0, Z = 0.2
G1 Z0.2 F7800
G1 X0 Y0 F7800
G1 X10 Y0 E1.0 F1800 ; single 10mm extrusion
